### ISSUE TITLE
点击事件监听有bug

### ISSUE THREAD

**Issue by hhzxxx** [M-cheng-web/web-tracing#1]
页面上多个data-warden-event-id绑定事件之后，连续点击，eventId都是最后一次点击的绑定id了。
![image](https://user-images.githubusercontent.com/62325706/150501021-283626b4-e42e-47d9-bdb1-a42e74327fed.png)

**Comment by hhzxxx** [comment]
应该是这里的问题，挪到里面就好了。
![image](https://user-images.githubusercontent.com/62325706/150506335-79a20e7e-c944-4b63-8955-19c1d24a4d92.png)

**Comment by M-cheng-web** [comment]
已修正并更新新版本 web-tracing@10.5.1  以及 @web-tracing/vue@1.5.1 
感谢您的帮助！！
