### ISSUE TITLE
请问作者二期大概啥时候完成呀？

### ISSUE THREAD

**Issue by shenyelengleng** [M-cheng-web/web-tracing#14]
请问作者二期的功能大概啥时候完成呀？另外我有个疑问就是，配套的后端代码在哪里呢？

**Comment by M-cheng-web** [comment]
二期已经完成了，针对于html，vue2，vue3的测试框架也都测试完毕；
目前正在编写文档阶段，如果在编写文档中觉得不合适的肯定可能会有很小的改动；
配套的后端代码目前是没有的，目前重心还是放在采集端；
三期我会做一套管理端+后面会用nest生态去完成后端；
java那一套我这就不考虑了，我也想提供多版本可耗时太多，如果有开源大佬相助我非常欢迎

**Comment by M-cheng-web** [comment]
已经完成了哦，具体可查看[文档](https://m-cheng-web.github.io/web-tracing/guide/use/options)，祝好~
