### ISSUE TITLE
参数类型问题

### ISSUE THREAD

**Issue by devcui** [M-cheng-web/web-tracing#15]
在二开时遇到一个问题如下

- 首先在 这一行 https://github.com/M-cheng-web/web-tracing/blob/9f68d06bf9aa48cc94524abbed66ccbbfa2b239b/packages/core/src/lib/eventBus.ts#L7 `callback`为`AnyFun`类型
- 在这一行 https://github.com/M-cheng-web/web-tracing/blob/9f68d06bf9aa48cc94524abbed66ccbbfa2b239b/packages/core/src/types/index.ts#L106 `AnyFun`定义为 `(...args: any[]): any`参数为数组并返回任意类型的函数
- 最后 https://github.com/M-cheng-web/web-tracing/blob/9f68d06bf9aa48cc94524abbed66ccbbfa2b239b/packages/core/src/lib/event.ts#L33 这一行，当使用`EventBus`为`click`事件添加处理函数时，实际上这里 参数为 `[MouseEvent] `导致接下来的代码运行失败

**Comment by M-cheng-web** [comment]
你好，首先感谢提出问题
"AnyFun定义为 (...args: any[]): any参数为数组并返回任意类型的函数" - 针对你说的这句话，我并不是定义 callback 函数的入参为数组，而是定义其入参的个数是任意个；
所以在最终使用时
callback: (e: MouseEvent) => {
}

**Comment by devcui** [comment]
感谢回复🙏，明天测一下，好梦

**Comment by M-cheng-web** [comment]
早安，如果还有更多问题可以入群随时问
