### ISSUE TITLE
线上vue3项目应该如何正确融合嵌入SDK？

### ISSUE THREAD

**Issue by Zqueen** [M-cheng-web/web-tracing#16]
需要把packages文件拷贝到项目中？且项目中package.json定义workspace吗？

**Comment by M-cheng-web** [comment]
不好意思哦，现在还不能用到生产环境；虽然代码写好了、demo项目也测试完毕；但目前还在编写文档，编写完文档会将最新代码发布到npm；预计本周五之前会发布npm

**Comment by Zqueen** [comment]
搓手期待

**Comment by M-cheng-web** [comment]
你好，抱歉久等，已经可以正常使用了哦；具体可查看示例项目：https://github.com/M-cheng-web/web-tracing-examples-vue3
