### ISSUE TITLE
web-tracing 二期开发已进入Beta阶段

### ISSUE THREAD

**Issue by M-cheng-web** [M-cheng-web/web-tracing#17]
文档已上线：https://m-cheng-web.github.io/web-tracing/

npm包版本：2.0.0-beta.5

// 核心实现包 - js
pnpm install @web-tracing/core

// vue2版本
pnpm install @web-tracing/vue2

// vue3版本
pnpm install @web-tracing/vue3

示例项目：
js：https://github.com/M-cheng-web/web-tracing-examples-js
vue2：https://github.com/M-cheng-web/web-tracing-examples-vue2
vue3：https://github.com/M-cheng-web/web-tracing-examples-vue3

**Comment by calandnong** [comment]
等待后端版本哇！

**Comment by M-cheng-web** [comment]
在肝了，在肝了😁

**Comment by wengfengtong** [comment]
期待

**Comment by M-cheng-web** [comment]
二期稳定版本 [2.0.1] 已上线，目前没有已知问题啦，希望各位能提出更多建议，作者本人正在肝nest服务端配套版，共勉！！！
