### ISSUE TITLE
上报的数据baseInfo里面数据有时候会缺失

### ISSUE THREAD

**Issue by xuyuqin0123** [M-cheng-web/web-tracing#24]
![image](https://github.com/M-cheng-web/web-tracing/assets/37656313/fb05c2be-b9b7-41a9-b547-51ebe4290840)

包括appCode,appName等参数都缺失了。主要出现在刷新和第一次进入的时候，随机性出现

**Comment by M-cheng-web** [comment]
版本、场景等一些详细信息麻烦提供一下，然后是否可以在demo项目中复现，谢谢理解

**Comment by xuyuqin0123** [comment]
我创建了一个简易版本的demo浮现了这个问题
![image](https://github.com/M-cheng-web/web-tracing/assets/37656313/7ecb14e3-8c8e-4ab3-b05e-acf2b0570d90)
我发现一旦html里面的link多起来。靠前的tracing链接就会出现这个问题
![image](https://github.com/M-cheng-web/web-tracing/assets/37656313/d061bed4-49b1-4965-990c-83922d202b1a)
这是我的html-demo的压缩包
[temp.zip](https://github.com/M-cheng-web/web-tracing/files/13278348/temp.zip)

**Comment by M-cheng-web** [comment]
[tracing-demo.zip](https://github.com/M-cheng-web/web-tracing/files/15228714/tracing-demo.zip)
你好，我这边按照你的demo试了下，木有并没有复现你的问题，你看看能否在我给的这个demo项目里复现或者是在https://github.com/M-cheng-web/web-tracing-examples-js 项目中复现？
