### ISSUE TITLE
我在ignoreErrors和ignoreRequest配置的接口没有效果

### ISSUE THREAD

**Issue by hytkxp** [M-cheng-web/web-tracing#25]
<img width="480" alt="image" src="https://github.com/M-cheng-web/web-tracing/assets/40634627/321f2952-045b-4295-935e-6838035cfbb8">
<img width="668" alt="image" src="https://github.com/M-cheng-web/web-tracing/assets/40634627/e42430b9-6927-4d2a-8bbf-ee980bb085b5">
接口上传的时候还是会上报上去

**Comment by M-cheng-web** [comment]
你好，我这边在demo项目上没有尝试了下，并没有复现，我的参数是：
ignoreRequest: [
    /.+\/loadFileLocaUNotSign.+/
  ],
这是我示例项目中部分的配置
Vue.use(WebTracing, {
  dsn: '/trackweb',
  // dsn: 'http://localhost:3351/trackweb',
  appName: 'cxh',
  debug: true,
  pv: true,
  performance: true,
  error: true,
  event: true,
  // localization: true,
  cacheMaxLength: 10,
  cacheWatingTime: 1000,
  userUuid: 'init_userUuid',
  sendTypeByXmlBody: true,
  recordScreen: true,

  scopeError: true,

  // tracesSampleRate: 0.5,

  // ignoreErrors: ['111', /^promise/, /.*split is not .* function/],
  ignoreRequest: [
    /getAllTracingList/,
    /cleanTracingList/,
    /.+\/loadFileLocaUNotSign.+/
  ],
}  


<img width="1436" alt="image" src="https://github.com/M-cheng-web/web-tracing/assets/58416262/8001d069-38e9-41e9-9ade-66d056bd567a">

**Comment by hytkxp** [comment]
我的配置用法和您的一样，但是就这个没有效果，不过我通过beforePushEventList勾子完成了我想要的效果
