### ISSUE TITLE
错误录屏的有的图标会丢失样式

### ISSUE THREAD

**Issue by hytkxp** [M-cheng-web/web-tracing#26]
目前发现只有图标和图片会出现这种情况
<img width="383" alt="image" src="https://github.com/M-cheng-web/web-tracing/assets/40634627/b9cdf00c-d1ee-4f0b-b606-4fb79a86d661">

还有一个问题想请教下，错误录屏我想延长最后结束的时刻如何做
因为我发现错误抛出的时候都是在最后一秒，画面可能还没有显示错误信息录屏就结束了
所以想知道如何在错误出来后，延后一两秒

**Comment by M-cheng-web** [comment]
你好
第一个问题：录屏功能我这边用的是rrweb，具体为什么出现图标样式丢失的情况，我大概上他们的issues看了下，是有一个解决方案，我这边就不提供这种兼容了

第二个问题：目前 [录屏相关逻辑](https://github.com/M-cheng-web/web-tracing/blob/main/packages/core/src/lib/recordscreen.ts) 并不支持在错误暴露后延迟几秒录屏操作，后续考虑支持把~
