### ISSUE TITLE
想问一下。如果想实现全埋点，应该怎么改造呀

### ISSUE THREAD

**Issue by baixjian** [M-cheng-web/web-tracing#27]

**Comment by M-cheng-web** [comment]
把目前所有的功能都打开即可，当然全部打开也满足不了这个场景：点击页面任一元素就上报一个事件，此sdk在点击埋点方面需要开发人员手动在标签上挂个属性，当然了，我是不太相信有人会采集用户在页面瞎点的事件，如果你们要采集的话，可以再留言，咱可以多沟通

**Comment by hytkxp** [comment]
很期待这个功能，有好处也有坏处，目前我的用法时手动挂标签，这样数据比较准确

**Comment by M-cheng-web** [comment]
> 很期待这个功能，有好处也有坏处，目前我的用法时手动挂标签，这样数据比较准确

好吧，我觉得 "点击页面任一元素就上报一个事件" 这种功能有些太浪费性能了，这样注定很多数据都是无效数据吧，但准确性是可以保证的，即使是多重嵌套经过我测试也没什么问题；

如果真有这种需求，我建议两个方案：
1.  如果是在vue，可以把每个元素都替换成私有的，自己任意决定是否添加
2. 搞定产品经理
