### ISSUE TITLE
xhr类型请求responseURL为空

### ISSUE THREAD

**Issue by lichenhuinn** [M-cheng-web/web-tracing#3]
![image](https://user-images.githubusercontent.com/44400146/174516766-f3e79626-a84b-4b94-a82b-3c3bf5829232.png)

this属性中的responseURL未空，这样赋值会将responseURL设置为空

**Comment by lichenhuinn** [comment]
/**
 * ajax, axios请求拦截
 */
function interceptAjax(performanceServer, errorServer) {
  const { open, send } = XMLHttpRequest.prototype;
  const _config = new RequestTemplate();
  // 劫持 open方法
  XMLHttpRequest.prototype.open = function openXHR(method, url, async) {
    _config.requestMethod = method;
    _config.src = url;
    return open.call(this, method, url, async);
  };
  // 劫持 send方法
  XMLHttpRequest.prototype.send = function(body) {
    // body 就是post方法携带的参数

    // readyState发生改变时触发,也就是请求状态改变时
    // readyState 会依次变为 2,3,4 也就是会触发三次这里
    this.addEventListener('readystatechange', () => {
      const {
        readyState,
        responseURL = _config.src,
        status,
        responseText,
      } = this;
      if (readyState === 4) { // 请求已完成,且响应已就绪
        if (status === 200 || status === 304) {
          if (performanceServer) {
            performance.tracePerformance('server', {
              src: responseURL,
              responseStatus: status,
              duration: Date.now() - _config.triggerTime,
              params: body ? body : undefined,
            });
          }
        } else if (errorServer) {
          console.log("ajax3333333333"+responseURL)
          error.traceError('server', responseText, {
            src: responseURL,
            responseStatus: status,
            params: body ? body : undefined,
          });
        }
      }
    });

    _config.triggerTime = Date.now();
    return send.call(this, body);
  };
}
中 
![image](https://user-images.githubusercontent.com/44400146/174942809-1bcfddea-2aaf-4796-ae2c-f3921f00891f.png)
这段获取src的代码，我认为这样写会导致eventInfo中的src中的属性为空

**Comment by M-cheng-web** [comment]
啊！ 不好意思，确实会有这种问题，感谢提出

**Comment by M-cheng-web** [comment]
这些会放在最新重构版本中，不好意思。

**Comment by M-cheng-web** [comment]
此问题已在二期中解决，感谢提出问题！！！
