### ISSUE TITLE
vue2引入@web-tracing/vue2报错

### ISSUE THREAD

**Issue by Annaze** [M-cheng-web/web-tracing#30]
SDK版本号: 2.0.4
使用vue-cli初始化的项目，只安装了@web-tracing/vue2
报错及依赖信息可参考图片
![微信截图_20240111173736](https://github.com/M-cheng-web/web-tracing/assets/39300584/1d2b7ba2-414c-4f1b-a45c-19c8a34eb699)
![222](https://github.com/M-cheng-web/web-tracing/assets/39300584/a5355a52-08ed-4e8a-9f09-ee446399d088)

**Comment by M-cheng-web** [comment]
呃呃呃，不好意思，你可以先自己装一下babel，后续我这边会考虑打包语法兼容

**Comment by Annaze** [comment]
使用babel-polyfill能解决这个报错，但是收到一条警告
![微信图片编辑_20240112101607](https://github.com/M-cheng-web/web-tracing/assets/39300584/692a880a-0971-4c39-8b3a-6cec6766752e)

**Comment by M-cheng-web** [comment]
是的，这个警告很久了，我最近比较忙，一直没空搞这个，初步怀疑是第三方引起的，不影响正常使用

**Comment by Annaze** [comment]
好的，谢谢
