### ISSUE TITLE
自动采集pv数据

### ISSUE THREAD

**Issue by mmclofe** [M-cheng-web/web-tracing#35]
1、自动采集pv数据的话支持传入params吗，我没想到解决方案。还是说这种业务场景的话直接让他手动调tracePageView上报pv数据
麻烦回复下我上面这个问题，谢谢

**Comment by M-cheng-web** [comment]
1. 初始化 web-tracing 时传入 ext，这个参数是全局参数，每次触发事件时都会带上，且这个参数是动态的，随时改，随时变 (文档地址: https://m-cheng-web.github.io/web-tracing/guide/use/options)
2. beforePushEventList 或者 beforeSendData 的钩子，判断事件的 eventType 是否为 pv 或者 pv-duration，随后再加入自定义参数 (文档地址： https://m-cheng-web.github.io/web-tracing/guide/functions/pv  文档地址：https://m-cheng-web.github.io/web-tracing/guide/functions/exports)
3. 如果是简单的参数你可以放在路由地址上，插件会把整个路由地址都放在事件参数内的
4. 也就是你说的方案，屏蔽pv自动采集改为手动采集，可自定义参数，但不建议，上面的方案中我推荐1或者2

**Comment by mmclofe** [comment]
![image](https://github.com/M-cheng-web/web-tracing/assets/44460247/9bcf7a0b-7530-4aa5-97e4-9b6c9e787d9f)
还有这个【SENDID】枚举跟事件参数中的【eventId】，我没看出来有对应关系呢，比如说采集pv数据eventId字段取得是【根据时间戳计算得来的字符】，点击事件eventId字段有相应其他的取值规则。我有点懵

**Comment by mmclofe** [comment]
> 1. 初始化 web-tracing 时传入 ext，这个参数是全局参数，每次触发事件时都会带上，且这个参数是动态的，随时改，随时变 (文档地址: https://m-cheng-web.github.io/web-tracing/guide/use/options)
> 2. beforePushEventList 或者 beforeSendData 的钩子，判断事件的 eventType 是否为 pv 或者 pv-duration，随后再加入自定义参数 (文档地址： https://m-cheng-web.github.io/web-tracing/guide/functions/pv  文档地址：https://m-cheng-web.github.io/web-tracing/guide/functions/exports)
> 3. 如果是简单的参数你可以放在路由地址上，插件会把整个路由地址都放在事件参数内的
> 4. 也就是你说的方案，屏蔽pv自动采集改为手动采集，可自定义参数，但不建议，上面的方案中我推荐1或者2

好的了解谢谢

**Comment by mmclofe** [comment]
> > ![image](https://private-user-images.githubusercontent.com/44460247/324666602-9bcf7a0b-7530-4aa5-97e4-9b6c9e787d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDAxNTgsIm5iZiI6MTcxMzgzOTg1OCwicGF0aCI6Ii80NDQ2MDI0Ny8zMjQ2NjY2MDItOWJjZjdhMGItNzUzMC00YWE1LTk3ZTQtOWI2YzllNzg3ZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWQ4MTA1ODAzMzE2MjlkYzk2MTliZGNjODZiNDBmYmJmMDU5YWVjNGE5NGNmYTYzZGY3YzA5ZGNhMjQwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLJskhscHRK7gHFa9mAb8P1wv5ymJnwD6ZXNg24Q7yg) 还有这个【SENDID】枚举跟事件参数中的【eventId】，我没看出来有对应关系呢，比如说采集pv数据eventId字段取得是【根据时间戳计算得来的字符】，点击事件eventId字段有相应其他的取值规则。我有点懵
> 
> SENDID 代表的是固定的 eventID，有些事件的 eventID 是变化的，例如点击事件的eventID 是在dom上自定义的，而pv的eventId也比较特殊，它取的是固定的应用id（当前应用ID，在整个页面生命周期内不变，单页应用路由变化也不会改变；加载SDK时创建且只创建一次）

我还是没理解到这个eventId字段的设计出来的作用，是出于什么考虑要设计成有些是固定的（同一类型事件上报上去eventId是一样的值），有些又是变化的，麻烦您解惑一下设计思想是什么，谢谢。

**Comment by M-cheng-web** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/44460247/324666602-9bcf7a0b-7530-4aa5-97e4-9b6c9e787d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDAxNTgsIm5iZiI6MTcxMzgzOTg1OCwicGF0aCI6Ii80NDQ2MDI0Ny8zMjQ2NjY2MDItOWJjZjdhMGItNzUzMC00YWE1LTk3ZTQtOWI2YzllNzg3ZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWQ4MTA1ODAzMzE2MjlkYzk2MTliZGNjODZiNDBmYmJmMDU5YWVjNGE5NGNmYTYzZGY3YzA5ZGNhMjQwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLJskhscHRK7gHFa9mAb8P1wv5ymJnwD6ZXNg24Q7yg) 还有这个【SENDID】枚举跟事件参数中的【eventId】，我没看出来有对应关系呢，比如说采集pv数据eventId字段取得是【根据时间戳计算得来的字符】，点击事件eventId字段有相应其他的取值规则。我有点懵
> > 
> > 
> > SENDID 代表的是固定的 eventID，有些事件的 eventID 是变化的，例如点击事件的eventID 是在dom上自定义的，而pv的eventId也比较特殊，它取的是固定的应用id（当前应用ID，在整个页面生命周期内不变，单页应用路由变化也不会改变；加载SDK时创建且只创建一次）
> 
> 我还是没理解到这个eventId字段的设计出来的作用，是出于什么考虑要设计成有些是固定的（同一类型事件上报上去eventId是一样的值），有些又是变化的，麻烦您解惑一下设计思想是什么，谢谢。


我一开始的初衷是为了让每个事件对象都有一个唯一的id，但后面做的过程可能逐渐把这个初衷给改掉了，eventid字段更像是eventtype字段的子级，一个细分的字段，例如eventype = error时，eventid可能为资源，也可能为资源、console.error

**Comment by mmclofe** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/44460247/324666602-9bcf7a0b-7530-4aa5-97e4-9b6c9e787d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDAxNTgsIm5iZiI6MTcxMzgzOTg1OCwicGF0aCI6Ii80NDQ2MDI0Ny8zMjQ2NjY2MDItOWJjZjdhMGItNzUzMC00YWE1LTk3ZTQtOWI2YzllNzg3ZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWQ4MTA1ODAzMzE2MjlkYzk2MTliZGNjODZiNDBmYmJmMDU5YWVjNGE5NGNmYTYzZGY3YzA5ZGNhMjQwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLJskhscHRK7gHFa9mAb8P1wv5ymJnwD6ZXNg24Q7yg) 还有这个【SENDID】枚举跟事件参数中的【eventId】，我没看出来有对应关系呢，比如说采集pv数据eventId字段取得是【根据时间戳计算得来的字符】，点击事件eventId字段有相应其他的取值规则。我有点懵
> > > 
> > > 
> > > SENDID 代表的是固定的 eventID，有些事件的 eventID 是变化的，例如点击事件的eventID 是在dom上自定义的，而pv的eventId也比较特殊，它取的是固定的应用id（当前应用ID，在整个页面生命周期内不变，单页应用路由变化也不会改变；加载SDK时创建且只创建一次）
> > 
> > 
> > 我还是没理解到这个eventId字段的设计出来的作用，是出于什么考虑要设计成有些是固定的（同一类型事件上报上去eventId是一样的值），有些又是变化的，麻烦您解惑一下设计思想是什么，谢谢。
> 
> 我一开始的初衷是为了让每个事件对象都有一个唯一的id，但后面做的过程可能逐渐把这个初衷给改掉了，eventid字段更像是eventtype字段的子级，一个细分的字段，例如eventype = error时，eventid可能为资源，也可能为资源、console.error

哦明白，我现在想的也是每个事件对象都有一个唯一的id，但看你设计的取值不是这样的所以问下你，谢谢解答，非常感谢！
