### ISSUE TITLE
npm run publish 报错

### ISSUE THREAD

**Issue by mmclofe** [M-cheng-web/web-tracing#36]
![image](https://github.com/M-cheng-web/web-tracing/assets/44460247/41df347a-c1fd-4e05-bcb0-fb641fb2e40c)
![de1c566e8d79b941da89c96e6deb280](https://github.com/M-cheng-web/web-tracing/assets/44460247/b84a0049-960d-4b63-8d4e-ada825d6b174)
您好，我想咨询下工程化方面的问题，如图，执行npm run publish 时在执行npm run build的过程中报错，我单一执行npm run build却不报错，这是为什么呢
node版本：20.12.2

**Comment by M-cheng-web** [comment]
第一张图给我的感觉是在 “execSync('npm run build', { stdio: 'inherit' })” 这里就报错了，你把其他的注释掉，看看这句能否正常执行？

**Comment by mmclofe** [comment]
> 第一张图给我的感觉是在 “execSync('npm run build', { stdio: 'inherit' })” 这里就报错了，你把其他的注释掉，看看这句能否正常执行？

对的，是这一步execSync('npm run build', { stdio: 'inherit' })就报错了，可能是node版本不对？

**Comment by mmclofe** [comment]
对不起打扰了，我的问题，我把你的LICENSE文件删了，看打包脚本里面有如下代码。。。
----- 复制 LICENSE 证书 -----
 for (const file of FILES_COPY_ROOT) {
  await fs.copyFile(path.join(rootDir, file), path.join(packageDist, file))
 }

**Comment by M-cheng-web** [comment]
哈哈哈，好的，ヾ(￣▽￣)Bye~Bye~
