### ISSUE TITLE
后期版本是否考虑事件录制?

### ISSUE THREAD

**Issue by wangxiaoze-view** [M-cheng-web/web-tracing#38]
目前本地体验是可以的这个工具也是有特点的，但如果后期考虑线上版本的话，我有几个问题需要询问一下：

1. 因为目前版本本地是最佳的效果，但是后期使用线上版本的话，在某些程度上用户由于操作错误导致的一些列问题，针对于这些问题是可以采集到错误问题；后端的告警日志前端的埋点问题貌似只能解决问题出现在哪里；好像也不清楚用户的操作行为(不能完全排除用户正常与非正常操作)

2. 是否后期会考虑视频录制问题？当报错或者操作不当的情况，会录制开始操作到结束15s的视频内容，**因为这个操作可能涉及到了用户的隐私情况** 这样也许就解决了上面的问题，也许这样就能清晰的知道用户是如何操作的呢

**Comment by M-cheng-web** [comment]
你好，不知道我的理解对不对，你是在问是否可以有录屏吗？
目前已有错误录屏，不过时长是5-10s且时长不可通过参数控制；如果你指的是其他任意事件的录屏，此类业务我个人认为是比较少的，如果有需要欢迎继续沟通

**Comment by wangxiaoze-view** [comment]
@M-cheng-web  是的，那这样的话 就非常完美了；

**Comment by M-cheng-web** [comment]
好，后续有需要欢迎沟通~
