### ISSUE TITLE
import 之后出现navigator notdefined报错

### ISSUE THREAD

**Issue by zuoheng1** [M-cheng-web/web-tracing#4]
![image](https://user-images.githubusercontent.com/75286244/174592648-66936189-daec-4d55-aa32-b8666ad08d6d.png)

**Comment by M-cheng-web** [comment]
你好, 不好意思给你带来问题了, 能否先提供下更多信息, 个人比较好奇的是, 你怎么会 import 引入 cjs 文件, import 是针对 esm 文件把

**Comment by zuoheng1** [comment]
感谢回复，如若方便，能否加微沟通(15621476909)万分感激
