### ISSUE TITLE
beforeSendData功能异常报错 导致页面白屏

### ISSUE THREAD

**Issue by wJiaaa** [M-cheng-web/web-tracing#43]
![image](https://github.com/M-cheng-web/web-tracing/assets/74813215/b6189e81-805b-4fd3-a8af-02fd7351bd11)
当配置项中的 recordScreen 为false 时候 会触发该情况。

**Comment by M-cheng-web** [comment]
已解决；
https://github.com/M-cheng-web/web-tracing/pull/45
