### ISSUE TITLE
埋点事件采集获取title字段流程图加载失败

### ISSUE THREAD

**Issue by Hollelihanqi** [M-cheng-web/web-tracing#5]
![image](https://user-images.githubusercontent.com/31592701/179648581-bd0e2b03-c58e-47c3-9f84-25b2710c3f3e.png)

**Comment by M-cheng-web** [comment]
好的 谢谢 我也在找原因,因为我是以gitee为图库的,本地能正常看到,线上就不行了,困惑

**Comment by M-cheng-web** [comment]
原因是图床出问题了，我这边再找其他的，可以看源码的图片地址，复制出来可以自己打开的
