### ISSUE TITLE
你这里文档跟实际传输的数据怎么很多不是一致的，比方说这个error，文档里面没有这个src字段，又比方同步异步资源加载那里，文档里面没有workerStart和sendTime

### ISSUE THREAD

**Issue by haolu077** [M-cheng-web/web-tracing#54]
![image](https://github.com/M-cheng-web/web-tracing/assets/116435452/a08e4e95-6784-418b-b398-19a2b92501bf)
![image](https://github.com/M-cheng-web/web-tracing/assets/116435452/f8bee5fc-e777-4c78-b460-25ebc231e837)
![image](https://github.com/M-cheng-web/web-tracing/assets/116435452/6016266c-8579-4f78-8ab5-81c958883652)
![image](https://github.com/M-cheng-web/web-tracing/assets/116435452/c2ab56b3-cf32-4e19-acc8-3c658f7cbc26)

**Comment by haolu077** [comment]
![a2a8f96ed140ffda0873ca9a534e067](https://github.com/M-cheng-web/web-tracing/assets/116435452/aa090000-5979-441a-9455-a2cf9b581bca)

**Comment by M-cheng-web** [comment]
1、 src字段是你在触发自定义事件时自己带上的，所以才会有；
2、资源这块的ts声明不是很清晰，考虑到兼容性问题一些不确定的属性我就不在文档上声明
3、sendTime 漏写了，但这种每个事件都会有的
