### ISSUE TITLE
这个userUuid、deviceId、sdkUserUuid有什么区别可以细讲一下吗

### ISSUE THREAD

**Issue by haolu077** [M-cheng-web/web-tracing#55]
![image](https://github.com/M-cheng-web/web-tracing/assets/116435452/ef818325-e16e-441c-a0b3-8a8511a2a65e)

**Comment by haolu077** [comment]
这里说的用户ID应该就是deviceId 吧

**Comment by haolu077** [comment]
然后我业务id用的应该是userId？

**Comment by M-cheng-web** [comment]
看你业务维度，一个是针对设备id，一个是你自己给用户的id

**Comment by haolu077** [comment]
然后你这整句话解释的是那个id
用户ID
每一次访问都有一个唯一的ID,不论什么时候来访问,用户是否登录,都携带有一个唯一的ID 可以理解为用来标记这个访问设备,有网卡mac地址则使用mac地址(移动端用udid) mac地址、移动端设备id,SDK生成的ID在库中的字段都为 udid

**Comment by haolu077** [comment]
好的，谢谢
