### ISSUE TITLE
关于图片埋点的功能

### ISSUE THREAD

**Issue by wssnail** [M-cheng-web/web-tracing#57]
对比了web-yea的web-see和另一个基于web-see的工具
目前发现还是web-tracing的上报数据结构更合理，内容更丰富，但是缺少img的埋点方式，这个后续会补充上吗？
感觉功能方面还是尽量在web-see这个前辈的基础上进行完善，尽量不做删减

**Comment by M-cheng-web** [comment]
感谢认可，我与 web-see 的作者也是老熟人了，非常感谢他；具体你说的img的埋点方式指的是？可以具体一点不

**Comment by wssnail** [comment]
> 感谢认可，我与 web-see 的作者也是老熟人了，非常感谢他；具体你说的img的埋点方式指的是？可以具体一点不

![clipbord_1721615547039](https://github.com/user-attachments/assets/87fa1c8b-20b1-43c2-b854-317129a17423)
在web-see里有一个useImgUpload配置

**Comment by wssnail** [comment]
> 感谢认可，我与 web-see 的作者也是老熟人了，非常感谢他；具体你说的img的埋点方式指的是？可以具体一点不

另外发现一个小问题，在处理axios请求异常的时候，ignoreRequest没生效，我在err.ts文件的259行做了一些调整
```ts
  // promise调用链未捕获异常
  // 只捕获未处理的 reject的错误，如果对reject进行了回调处理这边不进行捕获
  eventBus.addEvent({
    type: EVENTTYPES.UNHANDLEDREJECTION,
    callback: (e: PromiseRejectedResult) => {
      console.log('ERROR2', e)
      if (e.reason?.config?.url && isIgnoreHttp(e.reason.config.url)) return
      const errorInfo = parseErrorEvent(e)
      if (isIgnoreErrors(errorInfo)) return
      emit(errorInfo)
    }
  })
```

**Comment by M-cheng-web** [comment]
好的，你说的图片上传这个方式我这边并没有强制指定的，目前只有强制指定xml方式上传
