### ISSUE TITLE
默认是捕获页面上所有的click事件，但是没找到采集的过滤规则

### ISSUE THREAD

**Issue by gaomAndximi** [M-cheng-web/web-tracing#58]
文档上提到：捕获页面上所有的点击事件,主要原理是监听页面 click 事件，触发后根据规则判断是否采集事件以及获取该事件所需要的参数。但没有找到具体的例子

**Comment by M-cheng-web** [comment]
可以看看demo项目哈  https://github.com/M-cheng-web/web-tracing-examples-vue2
