### ISSUE TITLE
原生web用cdn引入时，主动上报事件失效

### ISSUE THREAD

**Issue by 5Reasons** [M-cheng-web/web-tracing#6]
想问问作者这个是我的操作有问题吗？引入方式p1，报错p2
<img width="575" alt="image" src="https://user-images.githubusercontent.com/61086064/187010956-ef10ce77-6f7d-44cd-a378-fc4165cf2178.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/61086064/187010972-f2148fae-4256-413e-8149-5ae39db6f9a1.png">

**Comment by M-cheng-web** [comment]
你好，你可以这样用： webtracing.methods.tracePerformance()

**Comment by 5Reasons** [comment]
谢谢！

**Comment by 5Reasons** [comment]
不好意思再次打扰，之前学校的项目需要引一个埋点系统、用了老哥的这个项目，之后我也在看您项目的源码来学习；之前没怎么接触过模块化、打包这方面的知识，看项目源码的时候发现rollup打包的入口文件(src/index.js) 好像没有上传到现在的这个仓库里，不知道方不方便参考一下和您要一下这个入口文件的代码呢~

**Comment by M-cheng-web** [comment]
不好意思，我这边没懂你想要哪块代码，可以贴图吗，据我所知我所有代码都上传了的，rollup这块我总结了个模板项目在github中的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "M-cheng-web/web-tracing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午5:48
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [M-cheng-web/web-tracing] 原生web用cdn引入时，主动上报事件失效 (Issue #6)





 
不好意思再次打扰，之前学校的项目需要引一个埋点系统、用了老哥的这个项目，之后我也在看您项目的源码来学习；之前没怎么接触过模块化、打包这方面的知识，看项目源码的时候发现rollup打包的入口文件(src/index.js) 好像没有上传到现在的这个仓库里，不知道方不方便参考一下和您要一下这个入口文件的代码呢~
