### ISSUE TITLE
1.0与main

### ISSUE THREAD

**Issue by JeremKeith** [M-cheng-web/web-tracing#61]
你好，我在阅读您的代码，我看1.0和main的差异很大，如果简单做一个pv、uv以及手动上报的埋点，并且是js脚本引入形式的，参考1.0的代码是否是一个好的选择？

**Comment by M-cheng-web** [comment]
尽量不要选择 1.0，我在做main的时候进行了很多改动，且修复了一些bug，如果你要自己做一个简单的js脚本，可以有两个选择
1. 基于1.0 分支，将主要代码copy过去，自己测测看看是否能满足你们的业务需求
2. 去拿main打包后的js文件，文件虽然比1.0大，但是你使用起来都和1.0一样的

**Comment by JeremKeith** [comment]
ok，多谢您的解答
