### ISSUE TITLE
iframe切换会导致数据上报cancel

### ISSUE THREAD

**Issue by cherishxtt** [M-cheng-web/web-tracing#63]
嵌套多个iframe模块，在每个iframe模块里面都进行了webTrace init，但是iframe切换的时候会导致上一个iframe数据上报接口取消

**Comment by M-cheng-web** [comment]
上报接口取消？没太明白，目前sdk内部是没有取消请求的逻辑的，在碰到这一类情况，推荐使用 sendBeacon方式发送数据

**Comment by cherishxtt** [comment]
> 上报接口取消？没太明白，目前sdk内部是没有取消请求的逻辑的，在碰到这一类情况，推荐使用 sendBeacon方式发送数据

使用sendBeacon方式是不是将sendTypeByXmlBody设为false就行了

**Comment by M-cheng-web** [comment]
不用特意设置 sendTypeByXmlBody ，内部默认是 sendBeacon
