### ISSUE TITLE
过了上报数据最大等待时间，但是没有触发上报

### ISSUE THREAD

**Issue by Roywhite** [M-cheng-web/web-tracing#64]
在页面刷新后，触发事件采集会立马上报，但是上报列表里没有刚刚的事件采集，并且过了上报数据最大等待时间，也没有自动上报，需要多次触发事件采集，把前面的一堆performance、pv...发完才会发送事件采集的数据（不会自动上报）
![image](https://github.com/user-attachments/assets/0056e58c-112f-4096-8613-fea3789b03e5)
![image](https://github.com/user-attachments/assets/f7083e7e-d3f0-4f6b-be18-6e5df65a3977)
![image](https://github.com/user-attachments/assets/ece815b4-c4c8-40c8-a2e6-4818cf942279)
![image](https://github.com/user-attachments/assets/7d498d59-4a27-4cef-a479-a3c43dc9e81e)
图上红框的第8个点击事件触发了我左边红框的请求，但是过了几分钟我再次点击该按钮时才被一起发送了
![image](https://github.com/user-attachments/assets/2f4304f9-36cf-43e4-8301-257f6cde5613)

**Comment by Roywhite** [comment]
将performance的core设置为false后就不会出现该问题了，因为第一次上报时只有几条数据。开启后刷新页面资源加载时会连续发送多个上报，但是并没有全部自动上报完成，以至于在触发事件上报时，仍在发送前面的上报数据

**Comment by M-cheng-web** [comment]
想了解一下，你那边目前情况是：事件捕获到了，但因为事件太多了排队导致较慢的问题吗，可以设置maxlength 大一点

**Comment by Roywhite** [comment]
对的，加大缓存区确实能解决该问题，感谢🙏
