### ISSUE TITLE
后端

### ISSUE THREAD

**Issue by Guoxm521** [M-cheng-web/web-tracing#65]
最近找前端监控相关的开源项目，发现这个项目真的超级赞，棒棒棒
然后很冒昧的问一下  关于这个项目的后端，有开源吗，也想学习一下

**Comment by Roywhite** [comment]
文档里有vue3的完整项目示例，https://github.com/M-cheng-web/web-tracing-examples-vue3，示例代码里用的就是express写的

**Comment by Guoxm521** [comment]
好嘞  感谢

**Comment by M-cheng-web** [comment]
目前后端只是简单的接收以及发放，能做的还有挺多，期待一下~

**Comment by Guoxm521** [comment]
很期待🌹，最近刚好在看前端监控这块的产品，也看了一些商业产品 如 webfuny  fundebug，看到他们那个后台感觉很不错。然后搜开源的项目 就关注到你的这个，真心很不错。看到你这边打算用nestjs 写那个后端，自己也想着借鉴你的前端，顺便学习一下nestjs 写一个后端
