### ISSUE TITLE
项目使用axios，并且get请求加上responseType: "blob"拿取图片信息实现剪贴板复制时，web-tracing会报错

### ISSUE THREAD

**Issue by Roywhite** [M-cheng-web/web-tracing#68]
示例代码：
![image](https://github.com/user-attachments/assets/63536d59-125e-4f49-8faa-c08b389e31a2)
报错信息：
```
Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').
```
![image](https://github.com/user-attachments/assets/0f0e2bad-8457-467c-9508-3dfc15c133bc)
![image](https://github.com/user-attachments/assets/c028503b-7743-4aec-92a1-fb1a18dbb874)

**Comment by Roywhite** [comment]
另外为什么会存在一些没有错误信息的code报错，控制台没有显示，去源代码里捕获已捕获/未捕获的报错也没有显示
![image](https://github.com/user-attachments/assets/4a07520c-c8b5-4d7c-9a3f-305fe08e8015)

**Comment by Roywhite** [comment]
#69 已提交修复

**Comment by Roywhite** [comment]
> 另外为什么会存在一些没有错误信息的code报错，控制台没有显示，去源代码里捕获已捕获/未捕获的报错也没有显示 ![image](https://private-user-images.githubusercontent.com/42577687/394549576-4a07520c-c8b5-4d7c-9a3f-305fe08e8015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTA4NzIsIm5iZiI6MTczMzg5MDU3MiwicGF0aCI6Ii80MjU3NzY4Ny8zOTQ1NDk1NzYtNGEwNzUyMGMtYzhiNS00ZDdjLTlhM2YtMzA1ZmUwOGU4MDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA0MTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Y2JlZTBjYjhiODljMzdkZGFkMmU5NWRjZTUxNzRlMGYwMTM0Y2ZkNWVjZDlmMDY0MTI1Mjk2NGNhZWEzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lz4kJufvURmUE3ClCSrdmclZibN248gQIQB83n1jvEo)
在发送前过滤掉了，完美！

**Comment by M-cheng-web** [comment]
是有这个缺陷，感谢指正
