### ISSUE TITLE
请问下 有重构roadmap吗

### ISSUE THREAD

**Issue by baixjian** [M-cheng-web/web-tracing#9]

**Comment by M-cheng-web** [comment]
你好，应该都会涉及到的，具体的我会在参阅神策等大平台的项目进行取舍

**Comment by hqzh** [comment]
放弃了吗

**Comment by M-cheng-web** [comment]
不可能放弃的，前段时间遭遇了裁员，最近才稳定下来，目前还在看各大平台源码以及学习nestjs相关的，因为后面也打算做一套服务端的配套

**Comment by M-cheng-web** [comment]
@hqzh @baixjian 感谢关注，我发布了最新的重构计划，期待你们的意见 #10
